server:
  port: 9200

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/msa?serverTimezone=Asia/Seoul
    #    url: jdbc:mysql://172.19.0.5:3306/msa?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#          ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        sql: debug

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      #      defaultZone: http://192.168.0.183:8761/eureka
#      defaultZone: http://127.0.0.1:8761/eureka
#  instance:
#    #    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    lease-expiration-duration-in-seconds: 30
#    lease-renewal-interval-in-seconds: 10
#    hostname: order-service

